---
AWSTemplateFormatVersion: 2010-09-09
Description: Provides the base security, IAM, and access configuration
Parameters:
  pOrganization:
    Description: The name of the portfolio that identifies its products, applications, and components
    Type: String
    MinLength: 1
    MaxLength: 30
    AllowedPattern: '[a-zA-Z0-9\-]*'
    Default: ${{ iapp.catalog.organization }}
  pPortfolio:
    Description: The name of the portfolio that identifies its products, applications, and components
    Type: String
    MinLength: 1
    MaxLength: 15
    AllowedPattern: '[a-zA-Z0-9\-]*'
    Default: ${{ iapp.catalog.portfolio }}
  pProduct:
    Description: The name of the product that identifies its applications and components
    Type: String
    MinLength: 1
    MaxLength: 15
    AllowedPattern: '[a-zA-Z0-9\-]*'
    Default: ${{ iapp.catalog.product }}
  pApplication:
    Description: The name of the application (or service module) that identifies its components
    Type: String
    MinLength: 1
    MaxLength: 15
    AllowedPattern: '[a-zA-Z0-9\-]*'
    Default: ${{ iapp.catalog.application }}
  pComponent:
    Description: The name of the component that aligns with the application or service module
    Type: String
    MinLength: 0
    MaxLength: 15
    AllowedPattern: '[a-zA-Z0-9\-]*'
    Default: ${{ iapp.catalog.component }}
  pDepartment:
    Description: The name of the department that owns the resource
    Type: String
    MinLength: 1
    MaxLength: 15
    AllowedPattern: '[a-zA-Z0-9\-]*'
    Default: ${{ iapp.catalog.department }}
  pEnvironment:
    Description: 'The name of the environment in which the resource is running (e.g.: sandbox, development, test, production)'
    Type: String
    MinLength: 1
    MaxLength: 15
    AllowedPattern: '[a-zA-Z0-9\-]*'
    Default: ${{ iapp.aws.environment }}
  pSupportEmail:
    Description: The email address of the support team to contact
    Type: String
    MinLength: 8
    MaxLength: 30
    AllowedPattern: (?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|"(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\[(?:(?:(2(5[0-5]|[0-4][0-9])|1[0-9][0-9]|[1-9]?[0-9]))\.){3}(?:(2(5[0-5]|[0-4][0-9])|1[0-9][0-9]|[1-9]?[0-9])|[a-z0-9-]*[a-z0-9]:(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21-\x5a\x53-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])+)\])
    Default: ${{ iapp.catalog.support_email }}
Resources:
  rArchConfRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ArchConfRole
      Description: 'Role that represents an ArchConf workshop participant'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCloud9User
        - arn:aws:iam::aws:policy/AWSCloud9EnvironmentMember
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action:
          - sts:AssumeRole
      Tags: 
        - 
          Key: "Name"
          Value: iapp-archconf-role
        - 
          Key: "iapp-organization"
          Value: 
            !Ref pOrganization
        - 
          Key: "iapp-portfolio"
          Value: 
            !Ref pPortfolio
        - 
          Key: "iapp-product"
          Value: 
            !Ref pProduct
        - 
          Key: "iapp-application"
          Value: 
            !Ref pApplication
        - 
          Key: "iapp-component"
          Value:
            !Ref pComponent
        - 
          Key: "iapp-department"
          Value:
            !Ref pDepartment
        - 
          Key: "iapp-environment"
          Value:
            !Ref pEnvironment
        - 
          Key: "iapp-support-email"
          Value:
            !Ref pSupportEmail    
  rArchConfProfile:
    DependsOn:
      - rArchConfRole
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: ArchConfProfile
      Path: /
      Roles:
      - !Ref rArchConfRole
  rArchConfGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: ArchConfWorkshopParticipants
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCloud9User
        - arn:aws:iam::aws:policy/AWSCloud9EnvironmentMember
        - arn:aws:iam::aws:policy/IAMUserChangePassword
      Path: /
  rArchConfPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: ArchConfDenyPolicy
      Description: 'Permissions denied to ArchConf workshop participants'
      PolicyDocument:
        Version: 2012-10-17
        Statement:
        - Sid: NoBilling
          Effect: Deny
          Action: aws-portal:*Billing
          Resource: '*'
        - Sid: NoCloudTrailChanges
          Effect: Deny
          Action:
          - cloudtrail:DeleteTrail
          - cloudtrail:StopLogging
          - cloudtrail:UpdateTrail
          Resource: '*'
        - Sid: NoKMS
          Effect: Deny
          Action:
          - kms:Create*
          - kms:Revoke*
          - kms:Enable*
          - kms:Get*
          - kms:Disable*
          - kms:Delete*
          - kms:Put*
          - kms:Update*
          Resource: '*'
      Roles:
      - !Ref rArchConfRole
      Groups:
      - !Ref rArchConfGroup
  rArchConfUser:
    DependsOn:
      - rArchConfGroup
    Type: AWS::IAM::User
    Properties: 
      UserName: ArchConfWorkshopUser
      Groups: 
        - !Ref rArchConfGroup
      LoginProfile: 
        Password: String
        PasswordResetRequired: true
      Tags: 
        - 
          Key: "Name"
          Value:
            !Sub iapp-archconf-user
        - 
          Key: "iapp-organization"
          Value: 
            !Ref pOrganization
        - 
          Key: "iapp-portfolio"
          Value: 
            !Ref pPortfolio
        - 
          Key: "iapp-product"
          Value: 
            !Ref pProduct
        - 
          Key: "iapp-application"
          Value: 
            !Ref pApplication
        - 
          Key: "iapp-component"
          Value:
            !Ref pComponent
        - 
          Key: "iapp-department"
          Value:
            !Ref pDepartment
        - 
          Key: "iapp-environment"
          Value:
            !Ref pEnvironment
        - 
          Key: "iapp-support-email"
          Value:
            !Ref pSupportEmail  
Outputs:
  rArchConfRoleName:
    Value: !Ref rArchConfRole
    Description: "Name of the ArchConf role"
    Export:
      Name: !Sub "shared:${pApplication}:role:name"
  rArchConfRoleArn:
    Value: !GetAtt rArchConfRole.Arn
    Description: "AWS arn of the ArchConf role"
    Export:
      Name: !Sub "shared:${pApplication}:role:arn"
  rArchConfGrpName:
    Value: !Ref rArchConfGroup
    Description: "Name of the ArchConf group"
    Export:
      Name: !Sub "shared:${pApplication}:group:name"
  rArchConfGrpArn:
    Value: !GetAtt rArchConfGroup.Arn
    Description: "AWS arn of the ArchConf group"
    Export:
      Name: !Sub "shared:${pApplication}:group:arn"
  rArchConfProfileName:
    Value: !Ref rArchConfProfile
    Description: "Name of the ArchConf profile"
    Export:
      Name: !Sub "shared:${pApplication}:profile:name"
  rArchConfProfileArn:
    Value: !GetAtt rArchConfProfile.Arn
    Description: "AWS arn of the ArchConf profile"
    Export:
      Name: !Sub "shared:${pApplication}:profile:arn"
  rArchConfUserArn:
    Value: !GetAtt rArchConfUser.Arn
    Description: "AWS arn of the ArchConf user"
    Export:
      Name: !Sub "shared:${pApplication}:user:arn"
  SourceCode:
    Description: The location of the source code for this CFT
    Value: 'https://github.com/dsietziapp/ArchConf'
...